---
title: "Best Title Ever"
date: 2019-04-05
---
author: GitHub Admin
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  It's a best github project ever.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
